% ცნობიერება

# შესავალი

რაკიღა კომპლექსებს რაღაც ნებელობა, ერთგვარი „მე“ გააჩნიათ, ამიტომ შიზოფრენულ
მდგომარეობაში მათ შეიძლება აიწყვიტონ და ისე გაუთამამდნენ ცნობიერ კონტროლს,
რომ შესაძლებელი გახდეს მათი დანახვა და მოსმენა. ისინი მოჩვენებებად გვეცხადებიან,
ისეთი ხმით ლაპარაკობენ, რომ მავან პირთა ხმები გეგონება. კომპლექსთა ასეთ
პერსონიფიკაციას ჯერ კიდევ აუცილებელი არაა პათოლოგიური ვუწოდოთ. სიზმრებში,
მაგალითად, ჩვენი კომპლექსები ხშირად პერსონიფიცირებული სახით გვევლინებიან. 
შესაძლებელია ისე გავვარჯიშდეთ, რომ სიფხიზლეშიც ვუყუროთ და ვუსმინოთ მათ.
გარკვეული სახის იოგას ვარჯიშების მიზანი სწორედ ცნობიერების მის შემადგენელ
კომპონენტებად გახლეჩვაში მდგომარეობს, რომელთაგან თითოეული ცალკეულ
პიროვნებად იჩენს თავს. ჩვენი არაცნობიერის ფსიქოლოგიაში არსებობენ ტიპიური
ფიგურები, რომელნიც სრულიად განსაზღვრული საკუთარი ცხოვრებით ცხოვრობენ.
ყოველივე ეს იმ გარემოებით აიხსნება, რომ ცნობიერების ე. წ. მთლიანობა ილუზიაა;
ფაქტიურად ეს მთლიანობა ლამაზი სიზმარია და სხვა არაფერი. სიამეს გვგვრის,
ვიფიქროთ, რომ ერთიანი ვართ, მაგრამ გადაჭრით შეიძლება ითქვას, რომ ასე არაა.
გამოდის, საკუთარ სახლში ბატონ-პატრონები არა ვყოფილვართ; კი, ვერაფერს იტყვი,
სასიამოვნო განცდაა, როცა გვწამს ჩვენი ნებისყოფისა, ენერგიისა და ყოველივე იმის, რისი
განხორციელებაც მიზნად დაგვისახავს; მაგრამ საქმე საქმეზე რომ მიდგება, ირკვევა, რომ
რაც გუნებაში გვქონდა, იმის მხოლოდ მცირედი ნაწილისთვის შეგვისხამს ფრთა, რადგან
ხელი შეგვიშალეს იმ პატარა ეშმაკუნებმა, – კომპლექსებმა. კომპლექსები ასოციაციათა
ავტონომიური ჯგუფებია, რომელთაც ტენდენცია აქვთ, დამოუკიდებლად იმოქმედონ,
თავის გემოზე იცხოვრონ, ჩვენს განზრახვებს კი ჩირადაც არ აგდებენ. ჩემის აზრით,
პიროვნული არაცნობიერი, ისევე როგორც კოლექტიური არაცნობიერი, კომპლექსთა ანუ
ნაწილ-პიროვნებათა განუსაზღვრელი, ჩვენთვის უცნობი რიცხვისაგან შედგება.
ასეთი წარმოდგენა ბევრ რამეს გვიხსნის. მაგალითად, ის შუქს ჰფენს იმ უბრალო
ფაქტს, რომ მგოსანს ძალუძს თავისი შინაგანი უნარების დრამატიზაცია და
პერსონიფიკაცია. როდესაც ის სცენარში, ლექსში, დრამასა თუ რომანში რაიმე ფიგურას
ქმნის, იქნებ ჰგონია, რომ ის მხოლოდ და მხოლოდ მისი ფანტაზიის ნაყოფია; ნურას
უკაცრავად, – ამ ფიგურამ გარკვეული აზრით თვითონ შექმნა საკუთარი თავი. არც ერთი
მწერალი თუ დრამატურგი არ დაეთანხმება იმ აზრს, რომ მის ფიგურებს რაიმე
ფსიქოლოგიური მნიშვნელობა გააჩნიათ, მაგრამ სინამდვილეში ამას წყალი არ გაუვა. ასე
რომ, მგოსნის მიერ შექმნილი ფიგურების შესწავლისას მის სამშვინველში ვიხედები.

# Body

ამრიგად, კომპლექსები ნაწილ-პიროვნებებია. როდესაც „მე“-კომპლექსზეა ლაპარაკი,
თავისთავად გასაგებად ვთვლით, რომ მას ცნობიერება უნდა გააჩნდეს, – ცნობიერებას
ხომ სხვადასხვა შინაარსთა კავშირს ვუწოდებთ ცენტრთან ანუ, სხვანაირად, „მე“-სთან.
მაგრამ სხვა კომპლექსებშიც ხომ არის შინაარსები ცენტრის, ერთგვარი nucleus-ის110
გარშემო დაჯგუფებული. ასე რომ, საკითხავია: აქვთ თუ არა კომპლექსებს საკუთარი
ცნობიერება? სპირიტისტულ ფენომენებს თუ შევისწავლით, იძულებული გავხდებით
ვაღიაროთ, რომ ე. წ. სულებს, რომელნიც ავტომატური წერის ანდა მედიუმის ხმის
მეშვეობით ვლინდებიან, მართლაც გააჩნიათ ერთგვარი საკუთარი ცნობიერება. ამიტომაა,
რომ საღად მოაზროვნე ხალხი მზადაა დაიჯეროს, რომ სულები – ეს გარდაცვლილი
დედის, თუ პაპის, ან სხვა ვინმეს სულია, – სწორედ იმ მეტად თუ ნაკლებად
გამოკვეთილი ინდივიდუალობის გამო, რომელიც ამ მანიფესტაციებში იჩენს თავს.
სულიერი ავადმყოფობის შემთხვევაში, რა თქმა უნდა, ჩვენთვის ნაკლებად უპრიანია
ვიფიქროთ, საქმე სულებთან გვაქვსო. ასეთ გამოვლინებებს მაშინ პათოლოგიურს
ვუწოდებთ ხოლმე. 

## Why are we here?

# Conclusion

# References

